---
# Simple docker-compose.yml
#
# Portainer environment variables:
# name-xyz = show enpass
#

version: '3'

services:
  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID: 1000
      - PGID: 1000
      - TZ: Europe/Zurich
    volumes:
      - vol_data:/config
    networks:
      - b_net_lan_default:
          ipv4_address: 172.28.1.147
    ports:
      - 8147:8181 #  <Host Port>:<Container Port>
volumes:
  vol_data:
networks:
   b_net_lan_default:
   external: true
