---
# Simple docker-compose.yml
#
# Portainer environment variables:
# name-xyz = show enpass
#

version: '3'

services:
  tautulli_app:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli_app
    restart: unless-stopped
    environment:
      - PUID: 1000
      - PGID: 1000
      - TZ: "Europe/Zurich"
   volumes:
      - vol_data:/config
    networks:
      - b_net_lan_default:        
   ports:
      - 8181:8181
volumes:
  vol_data:
networks:
   b_net_lan_default:
   external: true
