---
# Simple docker-compose.yml
#
# Portainer environment variables:
# name-xyz = show enpass
#
# Qnap: Create networks:
# docker network create -d qnet --opt=iface=bond0 --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet=10.10.10.0/24 --gateway=10.10.10.1 qnet_lan_dozzle
#

version: "3"

services:
  dozzle_app:
    image: amir20/dozzle:latest
    container_name: dozzle_app
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - vol_data:/var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      q_net_lan_dozzle:
        ipv4_address: 10.10.10.183
    ports:
      - 80:80 # <Host Port>:<Container Port>
volumes:
  vol_data:
networks:
  q_net_lan_dozzle:
   external: true
