# Simple docker-compose.yml
#
# Portainer environment variables:
# GOTIFY_DEFAULTUSER_PASS = show enpass
#
# Qnap: Create networks:
# docker network create -d qnet --opt=iface=bond0 --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet=10.10.10.0/24 --gateway=10.10.10.1 q_net_lan_gotify
#
version: '3'

services:
 gotify:
   image: gotify/server:latest
   container_name: gotify_app
   restart: unless-stopped
   environment:
     - GOTIFY_SERVER_PORT: 80
     - GOTIFY_SERVER_SSL_PORT: 443
     - GOTIFY_DEFAULTUSER_NAME: admin
     - GOTIFY_DEFAULTUSER_PASS: $GOTIFY_DEFAULTUSER_PASS
     - GOTIFY_DATABASE_DIALECT: sqlite3
     - GOTIFY_DATABASE_CONNECTION: db/gotify.db
   volumes:
     - vol_db:/db:/app/db
     - vol_data:/app/data
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
	networks:
      q_net_lan_gotify:
      ipv4_address: 10.10.10.183
	ports:
      - 80:80  
	  - 443:443
volumes:
  vol_data:
  vol_db:	 
networks:
  q_net_lan_gotify:
   external: true
