---
# Simple docker-compose.yml
#
# Portainer environment variables:
# WEBPASSWORD = show enpass
#
# Qnap: Create networks:
# docker network create -d qnet --opt=iface=bond0 --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet=10.10.10.0/24 --gateway=10.10.10.1 q_net_lan_pihole
#

version: "3"

services:
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      hostname: pihole.domain.xyz 
      restart: always
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
        TZ: Europe/Zurich
        WEBPASSWORD: $WEBPASSWORD        
      volumes:
        - vol_data:/etc-pihole:/etc/pihole
        - vol_data:/etc-dnsmasq.d:/etc/dnsmasq.d
      networks:
        q_net_lan_pihole:
          ipv4_address: 10.10.10.253
      ports:
        - 53:53/tcp # <Host Port>:<Container Port>
        - 53:53/udp # <Host Port>:<Container Port>
        - 80:80/tcp # <Host Port>:<Container Port>
volumes:
  vol_data:
networks:
 q_net_lan_pihole:
   external: true
