---
# Simple docker-compose.yml
#
# Portainer environment variables:
# WEBPASSWORD = show enpass
#
# Qnap: Create networks:
# docker network create -d qnet --opt=iface=bond0 --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet=10.10.10.0/24 --gateway=10.10.10.1 q_net_lan_pihole
#

version: "3"

services:
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      hostname: pihole.brainrouting.ccom 
      restart: always
      labels:
        - com.centurylinklabs.watchtower.enable=true
      environment:
        TZ: Europe/Zurich
        WEBPASSWORD: $WEBPASSWORD
        FTLCONF_LOCAL_IPV4: "10.10.10.101"
        DHCP_ACTIVE: true
        DHCP_START: "10.10.10.230"
        DHCP_END: "10.10.10.250"
        DHCP_LEASETIME: "2"
        PIHOLE_DOMAIN: "brainrouting.com"
        PIHOLE_DNS_: "9.9.9.10;149.112.112.10;1.1.1.1;1.0.0.1"
        DNS_BOGUS_PRIV: "False"
        DNS_FQDN_REQUIRED: "True"
        DNSMASQ_LISTENING: "all"
        TEMPERATUREUNIT: "c"
        WEBTHEME: "default-dark"
      cap_add:
      - NET_ADMIN      
      volumes:
        - vol_data:/etc-pihole:/etc/pihole
        - vol_data:/etc-dnsmasq.d:/etc/dnsmasq.d
      networks:
        q_net_lan_pihole:
          ipv4_address: 10.10.10.253
        b_net_int_default:
          ipv4_address: 172.25.1.253
      ports:
        - 53:53/tcp # <Host Port>:<Container Port>
        - 53:53/udp # <Host Port>:<Container Port>
        - 80:80/tcp # <Host Port>:<Container Port>
volumes:
  vol_data:
networks:
 q_net_lan_pihole:
   external: true
 b_net_int_default:
   external: true
