---
# Simple docker-compose.yml
#
# Portainer: Environment variables
# MYSQL_ROOT_PASSWORD = show enpass
# MYSQL_PASSWORD = show enpass
#
# Qnap: Create networks:
# docker network create -d bridge --subnet=172.28.1.0/24 --ip-range=172.28.1.0/24 --gateway=172.28.1.254 b_net_lan_default
#

version: '3'

services:
   guacd_app:
    image: guacamole/guacd:latest
    container_name: guacd_app
    restart: unless-stopped
    labels:
     - com.centurylinklabs.watchtower.enable=true
    volumes:
      - vol_data:/drive:/drive:rw
      - vol_data:/record:/record:rw
    networks:
       b_net_lan_default:    
         ipv4_address: 172.28.1.141       
   guac_db:
    image: mariadb:10.9.5
    container_name: guac_db
    restart: unless-stopped
    labels:
     - com.centurylinklabs.watchtower.enable=true
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - vol_db:/db-data:/var/lib/mysql
    networks:
       b_net_lan_default:
         ipv4_address: 172.28.1.142
   guacamole_app:
    image: guacamole/guacamole:latest
    container_name: guacamole_app
    restart: unless-stopped
    labels:
     - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - guac_db
      - guacd_app
    environment:
      GUACD_HOSTNAME: guacd_app
      MYSQL_HOSTNAME: guac_db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TOTP_ENABLED: true
    volumes:
      - vol_data:/config
    networks:
      b_net_lan_default:
       ipv4_address: 172.28.1.143
    ports:
      - 8010:8080      
volumes:
  vol_data:
  vol_db:
networks:
  b_net_lan_default:
    external: true
