---
# Simple docker-compose.yml
#
# Portainer: Environment variables
# MYSQL_ROOT_PASSWORD = show enpass
# MYSQL_PASSWORD = show enpass
#
# Qnap: Create networks:
# docker network create -d bridge --subnet=172.28.1.0/24 --ip-range=172.28.1.0/24 --gateway=172.28.1.254 b_net_lan_default
#
#  Within the 'guacamole' service. This will expose the guacamole webinterface directly
#  on port 8080 and you can use it for your own purposes.
#  Note: Guacamole is available on :8080/guacamole, not /.
#
# The initial login to the guacamole webinterface is:
#
#     Username: guacadmin
#     Password: guacadmin
#
# Make sure you change it immediately!
#

version: '3'

services:
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - guac_db
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guac_db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TOTP_ENABLED: true
    volumes:
      - vol_data:/config
    networks:
      b_net_lan_default:
        ipv4_address: 172.28.1.143
    ports:
      - 8080:8080/tcp # <Host Port>:<Container Port>
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped
    labels:
     - com.centurylinklabs.watchtower.enable=true
    volumes:
      - vol_data:/drive:/drive:rw
      - vol_data:/record:/record:rw
    networks:
      b_net_lan_default:    
        ipv4_address: 172.28.1.142
   guac_db:
    image: mariadb:10.9.5
    container_name: guac_db
    restart: unless-stopped
    labels:
     - com.centurylinklabs.watchtower.enable=true
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - vol_db:/db-data:/var/lib/mysql
    networks:
       b_net_lan_default:
         ipv4_address: 172.28.1.143
volumes:
  vol_data:
  vol_db:
networks:
  b_net_lan_default:
    external: true
