---
# Simple docker-compose.yml
#
# Portainer environment variables:
# name-xyz = show enpass
#

version: "3"
services:
  homepage_app:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage_app
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - vol_data:/app/config
      - vol_data:/var/run/docker.sock:ro
    networks:
      b_net_lan_default:
        ipv4_address: 172.28.1.146
    ports:
      - 8146:3000 # <Host Port>:<Container Port>
volumes:
  vol_data:
networks:
  b_net_lan_default:
    external: true
