---
# Simple docker-compose.yml
#
# Portainer environment variables:
# name-xyz = show enpass
#
# Qnap: Create networks:
# docker network create -d qnet --opt=iface=bond0 --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet=10.10.10.0/24 --gateway=10.10.10.1 q_net_lan_portainer
#

version: '3'

services:
  portainer_app:
    image: portainer/portainer-ce:latest
    container_name: portainer_app
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - vol_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - q_net_lan_portainer:
        ipv4_address: 10.10.10.191
     ports:
      - 8000:8000 # <Host Port>:<Container Port> Portainer API
      - 443:9443 # <Host Port>:<Container Port> Portainer Web UI https://host_ip:443
volumes:
  vol_data:
networks:
  q_net_lan_portainer:
    external: true
