---
# Simple docker-compose.yml
#
# Portainer environment variables:
# name-xyz = show enpass
#
# Qnap: Create networks:
# docker network create -d qnet --opt=iface=bond0 --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet=10.10.10.0/24 --gateway=10.10.10.1 q_net_lan_nginx
# docker network create -d bridge --subnet=172.25.1.0/24 --ip-range=172.25.1.0/24 --gateway=172.25.1.254 --internal b_net_int_default
#

version: "3"

services:
  nginx-proxy:
    image: 'docker.io/jc21/nginx-proxy-manager:2.10.4'
    container_name: nginx-proxy
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - vol_data:/data:/data
      - vol_data:/letsencrypt:/etc/letsencrypt
    networks:
      q_net_lan_nginx:
        ipv4_address: 10.10.10.194  
      b_net_int_default:
        ipv4_address: 172.25.1.195
    ports:
      - 80:80 # <port:host> : <port:container>
      - 443:443 # <port:host> : <port:container>      
volumes:
  vol_data:
networks:
   q_net_lan_nginx:
      external: true
   b_net_int_default:
      external: true      
