---
# Simple docker-compose.yml
#
# Portainer environment variables:
# name-xyz = show enpass
#
# Qnap: Create networks:
# docker network create -d qnet --opt=iface=bond0 --ipam-driver=qnet --ipam-opt=iface=bond0 --subnet=10.10.10.0/24 --gateway=10.10.10.1 q_net_lan_nginx
# docker network create -d bridge --subnet=172.28.1.0/24 --ip-range=172.28.1.0/24 --gateway=172.28.1.254 b_net_lan_default
# docker network create -d bridge --subnet=172.29.1.0/24 --ip-range=172.29.1.0/24 --gateway=172.29.1.254 b_net_dmz_default
#

version: "3"

services:
  nginx-proxy_app:
    image: 'docker.io/jc21/nginx-proxy-manager:2.10.4'
    container_name: nginx-proxy_app
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - vol_data:/data:/data
      - vol_data:/letsencrypt:/etc/letsencrypt
    networks:
      q_net_lan_nginx:
        ipv4_address: 10.10.10.194
      q_net_lan_pihole:
        ipv4_address: 10.10.10.195
      q_net_lan_dozzle:
        ipv4_address: 10.10.10.196
      q_net_lan_bookstack:
        ipv4_address: 10.10.10.197
      b_net_lan_default:
        ipv4_address: 172.28.1.194
      b_net_dmz_default:
        ipv4_address: 172.28.1.195
    ports:
      - 80:80 # <Host Port>:<Container Port>
      - 443:443 # <Host Port>:<Container Port>      
volumes:
  vol_data:
networks:
   q_net_lan_nginx:
      external: true
   q_net_lan_pihole:
      external: true
   q_net_lan_dozzle:
      external: true
   q_net_lan_bookstack:
      external: true
   b_net_lan_default::
      external: true
   b_net_dmz_default:
      external: true


      
